# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."bracket" = {
    image = "ghcr.io/evroon/bracket";
    environment = {
      "API_PREFIX" = "/api";
      "CORS_ORIGINS" = "http://localhost:8400";
      "ENVIRONMENT" = "DEVELOPMENT";
      "PG_DSN" = "postgresql://bracket_dev:bracket_dev@postgres:5432/bracket_dev";
      "SERVE_FRONTEND" = "true";
    };
    volumes = [
      "bracket_bracket_static_data:/app/static:rw"
    ];
    ports = [
      "8400:8400/tcp"
    ];
    dependsOn = [
      "bracket-postgres"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=bracket"
      "--network=bracket_bracket_lan"
    ];
  };
  systemd.services."podman-bracket" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-bracket_bracket_lan.service"
      "podman-volume-bracket_bracket_static_data.service"
    ];
    requires = [
      "podman-network-bracket_bracket_lan.service"
      "podman-volume-bracket_bracket_static_data.service"
    ];
    partOf = [
      "podman-compose-bracket-root.target"
    ];
    wantedBy = [
      "podman-compose-bracket-root.target"
    ];
  };
  virtualisation.oci-containers.containers."bracket-postgres" = {
    image = "postgres";
    environment = {
      "POSTGRES_DB" = "bracket_dev";
      "POSTGRES_PASSWORD" = "bracket_dev";
      "POSTGRES_USER" = "bracket_dev";
    };
    volumes = [
      "bracket_bracket_pg_data:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=postgres"
      "--network=bracket_bracket_lan"
    ];
  };
  systemd.services."podman-bracket-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-bracket_bracket_lan.service"
      "podman-volume-bracket_bracket_pg_data.service"
    ];
    requires = [
      "podman-network-bracket_bracket_lan.service"
      "podman-volume-bracket_bracket_pg_data.service"
    ];
    partOf = [
      "podman-compose-bracket-root.target"
    ];
    wantedBy = [
      "podman-compose-bracket-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-bracket_bracket_lan" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f bracket_bracket_lan";
    };
    script = ''
      podman network inspect bracket_bracket_lan || podman network create bracket_bracket_lan --driver=bridge
    '';
    partOf = [ "podman-compose-bracket-root.target" ];
    wantedBy = [ "podman-compose-bracket-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-bracket_bracket_pg_data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect bracket_bracket_pg_data || podman volume create bracket_bracket_pg_data
    '';
    partOf = [ "podman-compose-bracket-root.target" ];
    wantedBy = [ "podman-compose-bracket-root.target" ];
  };
  systemd.services."podman-volume-bracket_bracket_static_data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect bracket_bracket_static_data || podman volume create bracket_bracket_static_data
    '';
    partOf = [ "podman-compose-bracket-root.target" ];
    wantedBy = [ "podman-compose-bracket-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-bracket-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
