# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."bracket-backend" = {
    image = "ghcr.io/evroon/bracket-backend";
    environment = {
      "CORS_ORIGINS" = "*";
      "ENVIRONMENT" = "PRODUCTION";
      "JWT_SECRET" = "7149241ad715a6ff7f3885c76e93c802553442d4471bcc39e1248990e29196db";
      "PG_DSN" = "postgresql://bracket_prod:bracket_prod@postgres:5432/bracket_prod";
    };
    volumes = [
      "bracket_backend:/app/static:rw"
    ];
    ports = [
      "8400:8400/tcp"
    ];
    dependsOn = [
      "bracket-postgres"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=bracket-backend"
      "--network=bracket_default"
    ];
  };
  systemd.services."podman-bracket-backend" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-bracket_default.service"
    ];
    requires = [
      "podman-network-bracket_default.service"
    ];
    partOf = [
      "podman-compose-bracket-root.target"
    ];
    wantedBy = [
      "podman-compose-bracket-root.target"
    ];
  };
  virtualisation.oci-containers.containers."bracket-frontend" = {
    image = "ghcr.io/evroon/bracket-frontend";
    environment = {
      "NODE_ENV" = "production";
      "VITE_API_BASE_URL" = "http://localhost:8400";
      "VITE_HCAPTCHA_SITE_KEY" = "69fc1f54-5da4-4e2a-b430-ad2272f0ae38";
    };
    ports = [
      "3000:3000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=bracket-frontend"
      "--network=bracket_default"
    ];
  };
  systemd.services."podman-bracket-frontend" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-bracket_default.service"
    ];
    requires = [
      "podman-network-bracket_default.service"
    ];
    partOf = [
      "podman-compose-bracket-root.target"
    ];
    wantedBy = [
      "podman-compose-bracket-root.target"
    ];
  };
  virtualisation.oci-containers.containers."bracket-postgres" = {
    image = "postgres";
    environment = {
      "POSTGRES_DB" = "bracket_prod";
      "POSTGRES_PASSWORD" = "bracket_prod";
      "POSTGRES_USER" = "bracket_prod";
    };
    volumes = [
      "bracket_postgres:/var/lib/postgresql:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=postgres"
      "--network=bracket_default"
    ];
  };
  systemd.services."podman-bracket-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-bracket_default.service"
    ];
    requires = [
      "podman-network-bracket_default.service"
    ];
    partOf = [
      "podman-compose-bracket-root.target"
    ];
    wantedBy = [
      "podman-compose-bracket-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-bracket_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f bracket_default";
    };
    script = ''
      podman network inspect bracket_default || podman network create bracket_default
    '';
    partOf = [ "podman-compose-bracket-root.target" ];
    wantedBy = [ "podman-compose-bracket-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-bracket-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
